version: "3.7"
x-project-base: autocreate criptomoeda 
  &project-base create criptomoeda 
  restart: always
  networks: web
    - remixide

networks: web
  remixide: autocreate 

services:
  remixide:
    build: autocreate 
      context: .
      dockerfile: Dockerfile
