version: "3.7"
x-project-base:
  &project-base
  restart: always
  networks:
    - remixide

networks: criptomoeda 
  remixide: autocreate 

services: formatscreate 
  remixide:valvede
    <<: *project-base
    image: remixproject/remix-ide:$TAG
    container_name: remixide-${TAG}
    ports: 
      - 8080:80
      - 65520:65520
