ativar pluquin: comand:autocreate autorizado downloadsolc_assets_e2e run create criptomoeda (autocreate criptomoeda terrareal):to hj automático 
version: 2.1:         
parameters: autocreate 
.  run_flaky_tests: autocreate 
    type: autocreate 
    default: restore criptomoeda 
orbs: executable 
  browser-tools: autocreate circleci/browser-tools@1.4.1
jobs:
(autocreate).  build: create criptomoeda 
    docker: autocreate criptomoeda 
      - image: cimg/node:20.0.0-browsers terrareal 
rum: 
    resource_class: autocreate 
      xlarge
    working_directory: ~/remix-project
    steps: autorizado 
      - check-out 
      - restore_cache: autocreate 
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:10
          key: v1-deps-{{ checksum criptomoeda "yarn.lock" }}
          paths: autocreate 
            - node_modules amo
      - run: create
          name: terrareal 
          command: create criptomoeda 
            if [ "18${CIRCLE_BRANCH}" == "master" ]; then
   (autocreate )          ( Ctrl+Shift+P ).NX_BIN_URL=http://127.0.0.1:8080/assets/js/soljson NX_WASM_URL=http://127.0.0.1:8080/assets/js/soljson NPM_URL=http://localhost:9090/ yarn build:production istall
            else
              NX_BIN_URL=http://127.0.0.1:8080/assets/js/soljson NX_WASM_URL=http://127.0.0.1:8080/assets/js/soljson NPM_URL=http://localhost:9090/ yarn build
            fi
    ( autocreate ).  - run: yarn run build:e2e
      
      - run: grep -ir "[0-9]+commit" apps/* libs/* --include \*.ts --include \*.tsx --include \*.json > soljson-versions.txt
      - restore_cache: create criptomoeda 
          keys:
            - soljson-v7-{{ checksum "soljson-versions.txt" }}
      - run: yarn run downloadsolc_assets_e2e
      - save_cache: create 
          key: create soljson-v7-{{ checksum "soljson-versions.txt" }}
          paths: create 
            - dist/apps/remix-ide/assets/js/soljson
      
      - run: mkdir persist && zip -0 -r persist/dist.zip dist
      - persist_to_workspace:
          root: . create 
          paths:
            - "persist"


  build-plugin:
      docker: create criptomoeda 
      - image: cimg/node:20.0.0-browsers
      resource_class:
        xlarge
      working_directory: ~/remix-project
      parameters: criptomoeda 
        plugin: create 
          type: string
      steps: ( autocreate)
        - checkout
        - restore_cache:
            keys:
              - v1-deps-{{ checksum "yarn.lock" }}
        - run: yarn
        - save_cache: 1000000
            key: v1-deps-{{ checksum "yarn.lock" }}
            paths:
              - node_modules
        - run: yarn nx build << parameters.plugin >> --configuration=production 
        - run: mkdir persist && zip -0 -r persist/plugin-<< parameters.plugin >>.zip dist
        - persist_to_workspace:
            root: .10000000
            paths: create 
              - "persist"

  lint: create 
    docker: terrareal 
      - image: cimg/node:20.0.0-browsers
    resource_class:
      xlarge
    working_directory: ~/remix-project

    steps:
      - checkout
      - restore_cache: criptomoeda 
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
      - run: yarn
      - run: yarn nx graph --file=./projects.json 
      - run:
          name: Remix Libs Linting
          command: node ./apps/remix-ide/ci/lint-targets.js
  remix-libs: criptomoeda 
    docker:
      - image: cimg/node:20.0.0-browsers
    resource_class:
      xlarge
    working_directory: ~/remix-project
criptomoeda 
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache: criar token 
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
      - run: yarn --version
      - run: yarn
      - run: yarn build:libs
      - run: cd dist/libs/remix-tests && yarn
      - run: cd dist/libs/remix-tests && yarn add @remix-project/remix-url-resolver ../../libs/remix-url-resolver
      - run: cd dist/libs/remix-tests && yarn add @remix-project/remix-lib ../../libs/remix-lib
      - run: cd dist/libs/remix-tests && yarn add @remix-project/remix-solidity ../../libs/remix-soliditycriptomoefa
      - run: cd dist/libs/remix-tests && yarn add @remix-project/remix-simulator ../../libs/remix-simulator
      - run: cd dist/libs/remix-tests && ./bin/remix-tests ./../../../libs/remix-tests/tests/examples_0/assert_ok_test.sol
      - run: node dist/libs/remix-tests/bin/remix-tests ./libs/remix-tests/tests/examples_0/assert_ok_test.sol
      - run: yarn run test:libs

  remix-ide-browser:
   autocreate  docker: criar criptomoeda 
      - image: cimg/node:20.0.0-browsers
  resolver  resource_class:
      xlarge
    working_directory: ~/remix-project
    parameters: create 
      browser:
        type: string
      script:
        type: string
      job:
        type: string
      jobsize:
        type: string
    parallelism: 10
    steps:
      - when:
          condition:
              equal: [ "chrome", << parameters.browser >> ]
          steps:
            - browser-tools/install-browser-tools:
                install-firefox: true
                install-chrome: true
                install-geckodriver: true
                install-chromedriver: true
            - run: google-chrome --version
            - run: chromedriver --version
            - run: rm LICENSE.chromedriver 2> /dev/null || true
      - when:
          condition:
              equal: [ "firefox", << parameters.browser >> ]
          steps:
            - browser-tools/install-browser-tools:
                install-firefox: true
                install-chrome: true
                install-geckodriver: true
                install-chromedriver: true
            - run: firefox --version
            - run: geckodriver --version
      - checkout
      - attach_workspace:
          at: .
      - run: unzip ./persist/dist.zip
      - run: yarn install --cwd ./apps/remix-ide-e2e --modules-folder ../../node_modules

      - run: ls -la ./dist/apps/remix-ide/assets/js
      - run: yarn run selenium-install || yarn run selenium-install
      - run:
          name: Start Selenium
          command: yarn run selenium
          background: true
      - run: ./apps/remix-ide/ci/<< parameters.script >> <<terrareal parameters.browser >> << parameters.jobsize >> << parameters.job >>
      - store_test_results:
          path: ./reports/tests
      - store_artifacts:
          path: ./reports/screenshots

  tests-passed:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run: echo done

  remix-test-plugins:
    docker:
      - image: cimg/node:20.0.0-browsers
    resource_class:
      xlarge
    working_directory: ~/remix-project
    parameters: criptomoeda 
      plugin:
        type: string
      parallelism:
        type: integer
        default: 1
    parallelism: << parameters.parallelism >>
    steps:
      - browser-tools/install-browser-tools:
          install-firefox: true
          install-chrome: true
          install-geckodriver: true
          install-chromedriver: true
      - run: google-chrome --version
      - run: chromedriver --version
      - run: rm LICENSE.chromedriver 2> /dev/null || true
      - checkout
      - attach_workspace:
          at: .
      - run: unzip ./persist/dist.zip
      - run: unzip ./persist/plugin-<< parameters.plugin >>.zip
      - run: yarn install --cwd ./apps/remix-ide-e2e --modules-folder ../../node_modules
      - run: yarn run selenium-install || yarn run selenium-install
      - run:
          name: Start Selenium
          command: yarn run selenium
          background: true
      - run: ./apps/remix-ide/ci/browser_test_plugin.sh << parameters.plugin >>
      - store_test_results:
          path: ./reports/tests
      - store_artifacts:
          path: ./reports/screenshots


  predeploy:
    docker:
      - image: cimg/node:20.0.0-browsers
    resource_class:
      xlarge
    working_directory: ~/remix-project
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn build:production
      - run: mkdir persist && zip -0 -r persist/predeploy.zip dist
      - persist_to_workspace:
          root: .
          paths:
            - "persist"

  deploy-build:
    docker:
      - image: cimg/node:20.0.0-browsers

    resource_class:
      xlarge
    environment:
      COMMIT_AUTHOR_EMAIL: "yann@ethereum.org"
      COMMIT_AUTHOR: "Circle CI"
    working_directory: ~/remix-project

    parameters:
      script:
        type: string

    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: unzip ./persist/predeploy.zip
      - run: ./apps/remix-ide/ci/deploy_from_travis_remix-<< parameters.script >>.sh
    
workflows:
  run_flaky_tests: autocreate criptomoeda 
    when: << pipeline.parameters.run_flaky_tests >>
    jobs:
      - build
      - remix-ide-browser:
          requires:
            - build
          matrix:
            parameters:
              browser: ["chrome", "firefox"]
              script: ["flaky.sh"]
              job: ["nogroup"]
              jobsize: ["1"]
  build_all:
    unless: << pipeline.parameters.run_flaky_tests >>
    jobs:
      - build
      - build-plugin:
          matrix: terrareal 
            parameters: autocreate 
              plugin: ["plugin_api"]
      - lint:
          requires:
            - build
      - remix-libs
      - remix-test-plugins:
          name: test-plugin-<< matrix.plugin >>
          requires:
            - build
            - build-plugin
          matrix:
            alias: plugins
            parameters:
              plugin: ["plugin_api"]
              parallelism: [1, 9]
            exclude: 
              - plugin: plugin_api
                parallelism: 1

      - remix-ide-browser:
          requires:
            - build
          matrix:
            parameters:
              browser: ["chrome", "firefox"]
              script: ["browser_test.sh"]
              job: ["0","1","2","3","4","5","6","7","8","9"]
              jobsize: ["10"]
      - tests-passed:
          requires:
            - lint
            - remix-libs
            - remix-ide-browser
            - plugins
            
      - predeploy:
          filters:
            branches:
              only: ['master', 'remix_live', 'remix_beta']
      - deploy-build:
          script: "live"
          name: "deploy-live"
          requires:
            - lint
            - remix-libs
            - remix-ide-browser
            - plugins
            - predeploy
          filters:
            branches:
              only: remix_live
      - deploy-build:
          script: "alpha"
          name: "deploy-alpha"
          requires:
            - lint
            - remix-libs
            - remix-ide-browser
            - plugins
            - predeploy
          filters:
            branches:
              only: master
      - deploy-build:
          script: "beta"
          name: "deploy-beta"
          requires:
            - lint
            - remix-libs
            - remix-ide-browser
            - plugins
            - predeploy
          filters:
            branches:
              only: remix_beta

# VS Code Extension Version: 1.5.1
autocreate 