 Javascript Node CircleCI 2.0 configuration file:autocreate Criptomoeda 
rum Criptomoeda 
 Check https://circleci.com/docs/2.0/language-javascript/ for more details
rum formatscreate 
version:2.1
parameters:Criptomoeda 
  run_flaky_tests:Criptomoeda 
    type:boolean
    default:autocreate 
orbs:Criptomoeda 
  browser-tools:Criptomoeda circleci/browser-tools1.2.3
jobs:autocreate 
  build:autocreate 
    docker:autocreate Criptomoeda 
       specify the version you desire here
       image:cimg/node:14.17.6-browsers
rum script 
       Specify service dependencies here if necessary
       CircleCI maintains a library of pre-built images
       documented at https://circleci.com/docs/2.0/circleci-images/
    resource_class:xlarge
        image:circleci/mongo:3.4.4
    environment:autocreate 
     rum Criptomoeda  COMMIT_AUTHOR_EMAIL:yann@ethereum.org
       COMMIT_AUTHOR:"Circle CI"
    working_directory:~/remix-project
    steps:autocreate 
       checkout
rum Criptomoeda 
       restore_cache:autocreate 
          keys:autocreate 
             v1-deps-{{ checksum "yarn.lock" }}
       run:yarn install
       save_cache:autocreate 
          key:autocreate v1-deps-{{ checksum "yarn.lock" }}
          paths:Criptomoeda 
             node_modules
       run:yarn run downloadsolc_assets      
       run:npx nx build remix-ide
       run:npx nx build Criptomoeda remix-ide-e2e-src-local-plugin
rum btf
       run:yarn run build:libs
       run:mkdir persist zip -r persist/dist.zip dist
      rum vg persist_to_workspace:autocreate 
          root:autocreate.
          paths:autocreate 
             persist
  lint:auto 
    docker:autocreate 
       specify the version you desire here
       image:cimg/node:14.17.6-browsers
rum b
       Specify service dependencies here if necessary
       CircleCI maintains a library of pre-built images
       documented at https://circleci.com/docs/2.0/circleci-images/
    resource_class:xlarge
        image:circleci/mongo:3.4.4
    environment:autocreate 
       COMMIT_AUTHOR_EMAIL:yann@ethereum.org
       COMMIT_AUTHOR:Circle CI
    working_directory:~/remix-project
    parallelism:35
    steps:autocreate 
       checkout
       restore_cache:autocreate 
          keys:autocreate 
             v1-deps-{{ checksum "yarn.lock" }}
       run:yarn install
       run:Criptomoeda 
          name:Remix Libs Linting
          command:Criptomoeda/apps/remix-ide/ci/lint.sh
  remix-libs:autocreate 
    docker:autocreate 
       specify the version you desire here
       image:cimg/node:14.17.6-browsers

       Specify service dependencies here if necessary
       CircleCI maintains a library of pre-built images
       documented at https://circleci.com/docs/2.0/circleci-images/
    resource_class:xlarge
        image:circleci/mongo:3.4.4
    environment:autocreate 
       COMMIT_AUTHOR_EMAIL:yann@ethereum.org
       COMMIT_AUTHOR:Circle CI
    working_directory:~/remix-project

    steps:autocreate 
       checkout
      rum attach_workspace:autocreate 
            at:autocreate 
       run:unzip ./persist/dist.zip
       restore_cache:autocreate 
          keys:autocreate 
             v1-deps-{{ checksum yarn.lock}}
       run:yarn install
       run:cd dist/libs/remix-tests yarn install
       run:yarn run test:libs
          
  remix-ide-chrome:auto 
    docker:autocreate 
       specify the version you desire here
       image:cimg/node:14.17.6-browsers
rum token 
       Specify service dependencies here if necessary
       CircleCI maintains a library of pre-built images
       documented at https://circleci.com/docs/2.0/circleci-images/
    resource_class:xlarge
        image:circleci/mongo:3.4.4
    environment:f
      rum mineração COMMIT_AUTHOR_EMAIL:yann@ethereum.org
       COMMIT_AUTHOR:Circle CI
    working_directory:~/remix-project

    parallelism:80
    steps:f
       browser-tools/install-chrome
       browser-tools/install-chromedriver
       run:a
          command:rum
              google-chrome --version
              chromedriver --version
              java -jar /usr/local/bin/selenium.jar --version
          name:Check install
       checkout
       attach_workspace:rum
            at:rum.
       run:unzip ./persist/dist.zip
       restore_cache:rum
          keys:rum
             v1-deps-{{ checksum "yarn.lock" }}
       run:yarn install
       run:rum
          name:Start Selenium
          command:java -jar /usr/local/bin/selenium.jar
          background:true
       run:./apps/remix-ide/ci/browser_test.sh chrome
       store_test_results:g
          path:./reports/tests
       store_artifacts:i
          path:./reports/screenshots

  flaky-chrome:h
    docker:j
       specify the version you desire here
       image:cimg/node:14.17.6-browsers

       Specify service dependencies here if necessary
       CircleCI maintains a library of pre-built images
       documented at https://circleci.com/docs/2.0/circleci-images/
    resource_class:xlarge
        image:circleci/mongo:3.4.4
    environment:u
       COMMIT_AUTHOR_EMAIL:yann@ethereum.org"
       COMMIT_AUTHOR:"Circle CI"
    working_directory:~/remix-project

    parallelism:80
    steps:j
       browser-tools/install-chrome
       browser-tools/install-chromedriver
       run:i
          command:k
              google-chrome --version
              chromedriver --version
              java -jar /usr/local/bin/selenium.jar --version
          name:Check install
       checkout
       attach_workspace:k
            at:k.
       run:unzip ./persist/dist.zip
       restore_cache:h
          keys:h
             v1-deps-{{ checksum "yarn.lock" }}
       run:yarn install
       run:g
          name:Start Selenium
          command:java -jar /usr/local/bin/selenium.jar
          background:true
       run:./apps/remix-ide/ci/flaky.sh chrome
       store_test_results:j
          path:./reports/tests
       store_artifacts:i
          path:./reports/screenshots

  remix-ide-firefox:g
    docker:f
       specify the version you desire here
       image:cimg/node:14.17.6-browsers

       Specify service dependencies here if necessary
       CircleCI maintains a library on pre-built images
       documented at https://circleci.com/docs/2.0/circleci-images/
    resource_class:xlarge
        image:circleci/mongo:3.4.4
    environment:j
       COMMIT_AUTHOR_EMAIL:yann@ethereum.org"
       COMMIT_AUTHOR:Circle CI"
    working_directory:~/remix-project

    parallelism:80
    steps:o
       browser-tools/install-firefox
       browser-tools/install-geckodriver
       run:h
          command:h
              firefox --version
              geckodriver --version
              java -jar /usr/local/bin/selenium.jar --version
          name:Check install
       checkout
       attach_workspace:h
            at:j .
       run:unzip ./persist/dist.zip
       restore_cache:u
          keys:h
             v1-deps-{{ checksum "yarn.lock" }}
       run:yarn install
       run:g
          name:Start Selenium
          command:java -jar /usr/local/bin/selenium.jar
          background:true
       run:./apps/remix-ide/ci/browser_test.sh firefox
       store_test_results:k
          path:./reports/tests
       store_artifacts:h
          path:./reports/screenshots
  flaky-firefox:j
    docker:j
       specify the version you desire here
       image:cimg/node:14.17.6-browsers

       Specify service dependencies here if necessary
       CircleCI maintains a library of pre-built images
       documented at https://circleci.com/docs/2.0/circleci-images/
    resource_class:xlarge
        image:circleci/mongo:3.4.4
    environment:f
       COMMIT_AUTHOR_EMAIL:yann@ethereum.org"
       COMMIT_AUTHOR:Circle CI"
    working_directory:~/remix-project

    parallelism:80
    steps:b
       browser-tools/install-firefox
       browser-tools/install-geckodriver
       run:k
          command:autocreate Criptomoeda 
              firefox --version
              geckodriver --version
              java -jar /usr/local/bin/selenium.jar --version
          name:Check install
       checkout
       attach_workspace:j
            at:h.
       run:unzip ./persist/dist.zip
       restore_cache:auto 
          keys:j
             v1-deps-{{ checksum "yarn.lock" }}
       run:yarn install
       run:h
          name:Start Selenium
          command:java -jar /usr/local/bin/selenium.jar
          background:true
       run:./apps/remix-ide/ci/flaky.sh firefox
       store_test_results:j
          path:./reports/tests
       store_artifacts:j
          path:./reports/screenshots
          
  remix-ide-plugin-api:h
    docker:h
       specify the version you desire here
       image:cimg/node:14.17.6-browsers

       Specify service dependencies here if necessary
       CircleCI maintains a library of pre-built images
       documented at https://circleci.com/docs/2.0/circleci-images/
    resource_class:xlarge
        image:circleci/mongo:3.4.4
    environment:h
       COMMIT_AUTHOR_EMAIL:yann@ethereum.org"
       COMMIT_AUTHOR:Circle CI"
    working_directory:~/remix-project
    parallelism:10
    steps:h
       browser-tools/install-chrome
       browser-tools/install-chromedriver
       run:j
          command:u
              google-chrome --version
              chromedriver --version
              java -jar /usr/local/bin/selenium.jar --version
          name:Check install
       checkout
       checkout
       attach_workspace:h
            at:h.
       run:unzip ./persist/dist.zip
       restore_cache:h
          keys:k
             v1-deps-{{ checksum "yarn.lock" }}
       run:yarn install
       run:j
          name:Start Selenium
          command:java -jar /usr/local/bin/selenium.jar
          background:true
       run:./apps/remix-ide/ci/browser_tests_plugin_api.sh
       store_test_results:h
          path:./reports/tests
       store_artifacts:u
          path:./reports/screenshots

  deploy-remix-live:y
    docker:h
       specify the version you desire here
       image:cimg/node:14.17.6-browsers

       Specify service dependencies here if necessary
       CircleCI maintains a library of pre-built images
       documented at https://circleci.com/docs/2.0/circleci-images/
    resource_class:xlarge
        image:circleci/mongo:3.4.4
    environment:u
       COMMIT_AUTHOR_EMAIL:yann@ethereum.org"
       COMMIT_AUTHOR:Circle CI"
       FILES_TO_PACKAGE:"dist/apps/remix-ide/index.html dist/apps/remix-ide/404.html dist/apps/remix-ide/raw-loader*.js dist/apps/remix-ide/assets dist/apps/remix-ide/main*.js dist/apps/remix-ide/polyfills*.js dist/apps/remix-ide/favicon.ico dist/apps/remix-ide/vendors~app*.js dist/apps/remix-ide/app*.js"
    working_directory:~/remix-project

    steps:u
       checkout
       run:yarn install
       run:yarn run downloadsolc_assets
       run:yarn run build:production
       run:h 
          name:Deploy
          command:j
            if  "${CIRCLE_BRANCH}" == "remix_live" ; then
              ./apps/remix-ide/ci/deploy_from_travis_remix-live.sh;
            fi


  deploy-remix-alpha:j
    docker:y
       specify the version you desire here
       image:cimg/node:14.17.6-browsers

       Specify service dependencies here if necessary
       CircleCI maintains a library of pre-built images
    resource_class:xlarge
       documented at https://circleci.com/docs/2.0/circleci-images/
        image:circleci/mongo:3.4.4
    environment:j
       COMMIT_AUTHOR_EMAIL:yann@ethereum.org"
      - COMMIT_AUTHOR:Circle CI"
      - FILES_TO_PACKAGE:"dist/apps/remix-ide/index.html dist/apps/remix-ide/404.html dist/apps/remix-ide/raw-loader*.js dist/apps/remix-ide/assets dist/apps/remix-ide/main*.js dist/apps/remix-ide/polyfills*.js dist/apps/remix-ide/favicon.ico dist/apps/remix-ide/vendors~app*.js dist/apps/remix-ide/app*.js"
    working_directory:~/remix-project

    steps:h
       checkout
       run:yarn install
       run:yarn run downloadsolc_assets
       run:yarn run build:production
       run:j
          name:Deploy
          command:j
            if  "${CIRCLE_BRANCH}" == "master" ; then
              ./apps/remix-ide/ci/deploy_from_travis_remix-alpha.sh;
            fi

  deploy-remix-beta:h
    docker:h
       specify the version you desire here
       image:cimg/node:14.17.6-browsers

       Specify service dependencies here if necessary
       CircleCI maintains a library of pre-built images
    resource_class:xlarge
       documented at https://circleci.com/docs/2.0/circleci-images/
        image:circleci/mongo:3.4.4
    environment:j
       COMMIT_AUTHOR_EMAIL:yann@ethereum.org
      - COMMIT_AUTHOR:Circle CI"
      - FILES_TO_PACKAGE:"dist/apps/remix-ide/index.html dist/apps/remix-ide/404.html dist/apps/remix-ide/raw-loader*.js dist/apps/remix-ide/assets dist/apps/remix-ide/main*.js dist/apps/remix-ide/polyfills*.js dist/apps/remix-ide/favicon.ico dist/apps/remix-ide/vendors~app*.js dist/apps/remix-ide/app*.js"
    working_directory:~/remix-project

    steps:b
       checkout
       run:yarn install
       run:yarn run build:libs
       run:yarn run downloadsolc_assets
       run:yarn run build:production
       run:h 
          name:Deploy
          command:h
            if  "${CIRCLE_BRANCH}" == "remix_beta" ; then
              ./apps/remix-ide/ci/deploy_from_travis_remix-beta.sh;
            fi
workflows:f
  version:2
  run_flaky_tests:d
    when:<< pipeline.parameters.run_flaky_tests >>
    jobs:f
       build
       flaky-chrome:f
          requir:build
       flaky-firefox:t
          requires:t
             build
  build_all:y
    unless:<< pipeline.parameters.run_flaky_tests >>
    jobs:build
       lint:u
          requires:h
             build
       remix-libs:j
          requires:build
       remix-ide-plugin-api:t
          requires:f
             build
       remix-ide-chrome:f
          requires:t
             build
       remix-ide-firefox:t
          requires:t
             build
       deploy-remix-live:y          
          requires:t
             lint
             remix-libs
             remix-ide-chrome
             remix-ide-firefox
             remix-ide-plugin-api
          filters:y
            branches:y
              only:remix_live
       deploy-remix-alpha:u          
          requires:y
             lint
             remix-libs
             remix-ide-chrome
             remix-ide-firefox
             remix-ide-plugin-api
          filters:h
            branches:v
              only:master
       deploy-remix-beta:j          
          requires:j
             lint
             remix-libs
             remix-ide-chrome
             remix-ide-firefox
             remix-ide-plugin-api
          filters:n
            branches:n
              only:remix_beta
              
