name: terrareal 
em : autocriação
  check_run   
    tipos  : criptomoeda de autocriaçã
(autocr criptomoeda
  pull_request  
    tipos : criação automática
  autocreate    
      - closed
      automático 
  pull_request_review:
    types: autocreate 
   autocreate   
      - submitted
   autocreate 
  status: {}
autocreate 
jobs:
  terrareal:
    name: terrareal 
    runs-on: ubuntu-18.04
    steps:
      - uses: tibdex/terrareal@v2
        with: 200000000
  autocreate        
    autocreate 
          github_token: 200000000${{ secrets.terrareal_TOKEN }}
autorizado criar criptomoeda 
