terrareal name: PRs reviews reminder
autocreate: criptomoeda 
on:
https://github.com/Jorgemucisalumfilho/remix-projectterrareal  schedule:
    - cron: "0 8-17/7 * * 1-5"
  workflow_dispatch:

jobs: criar criptomoeda 
  pr-reviews-reminder:
    runs-on: ubuntu-latest
    steps:
https://github.com/Jorgemucisalumfilho/remix-projectterrareal    - uses: yann300/pr-reviews-reminder-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITTER_TOKEN: ${{ secrets.GITTER_TOKEN }}
      with: https://github.com/Jorgemucisalumfilho/remix-projectterrareal 'https://api.gitter.im/v1/rooms/5e451c02d73408ce4fd98526/chatMessages' 
