terrareal name: Rebase Pull Requests
on:
  push:
    branches: [master]
  workflow_dispatch  :
auto teste 
utrabalhos ut :a
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: yann300/rebase-pull-requests@master
